feat: Add task to create image pull secret for private registry

diff --git a/k8s/Taskfile.yaml b/k8s/Taskfile.yaml
--- a/k8s/Taskfile.yaml
+++ b/k8s/Taskfile.yaml
@@ -29,6 +29,21 @@ tasks:
     cmds:
       - "kubectl apply -f ./frontend"
 
+  backend:create-image-pull-secret:
+    desc: "Create image pull secret to pull from private registry"
+    cmds:
+      - |
+        if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_EMAIL" ] || [ -z "$DOCKER_PASSWORD" ]; then
+          echo "Environment variables DOCKER_USERNAME, DOCKER_EMAIL, and DOCKER_PASSWORD are required."
+          echo "Usage: DOCKER_USERNAME=your_username DOCKER_EMAIL=your_email DOCKER_PASSWORD=your_password task backend:create-image-pull-secret"
+          exit 1
+        fi
+      - |
+        kubectl create secret -n microadventures docker-registry dockerconfigjson \
+          --docker-email=${DOCKER_EMAIL} \
+          --docker-username=${DOCKER_USERNAME} \
+          --docker-password=${DOCKER_PASSWORD} \
+          --docker-server=https://index.docker.io/v1/
 
   apply-all:
     desc: "Apply kubernetes resource manifests for all applications"
